// Generated by CoffeeScript 1.9.0
(function(doc) {
  var data, firstResultTime, result, _i, _len, _ref;
  if (doc.from) {
    data = {
      invalidResult: {},
      validIndices: []
    };
    firstResultTime = null;
    _ref = doc.results;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      result = _ref[_i];
      if (!firstResultTime) {
        firstResultTime = result.datetime;
      }
      if (result.valid !== true) {
        data.invalidResult[result.question_index] = result.answer;
      }
      if (result.valid) {
        data.validIndices.push(result.question_index);
      }
    }
    data["from"] = doc.from;
    data["firstResultTime"] = firstResultTime;
    data["updatedAt"] = doc.updated_at;
    data["complete"] = doc.complete;
    return emit([doc.question_set, firstResultTime], data);
  }
});

//# sourceMappingURL=map.js.map
