// Generated by CoffeeScript 1.8.0
var Gooseberry;

Gooseberry = {
  config: {
    database: "gooseberry",
    designDoc: "gooseberry"
  }
};

Backbone.couch_connector.config.db_name = Gooseberry.config.database;

Backbone.couch_connector.config.ddoc_name = Gooseberry.config.designDoc;

Backbone.couch_connector.config.global_changes = true;

Gooseberry.view = function(options) {
  return $.couch.db(Gooseberry.config.database).view(Gooseberry.config.designDoc + "/" + options.name, options);
};

Gooseberry.save = function(options) {
  return $.couch.db(Gooseberry.config.database).saveDoc(options.doc, options);
};

Gooseberry.router = new Router();

Backbone.history.start();

Gooseberry.debug = function(string) {
  console.log(string);
  return $("#log").append(string + "<br/>");
};

//# sourceMappingURL=Gooseberry.js.map
