// Generated by CoffeeScript 1.8.0
var Router,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Router = (function(_super) {
  __extends(Router, _super);

  function Router() {
    return Router.__super__.constructor.apply(this, arguments);
  }

  Router.prototype.routes = {
    "": "questionSets",
    "question_sets": "questionSets",
    "question_set/:name": "questionSet",
    "question_set/:name/edit": "editQuestionSet",
    "question_set/:name/results": "questionSetResults",
    '*invalidRoute': 'showErrorPage'
  };

  Router.prototype.questionSets = function() {
    if (!Gooseberry.questionSetView) {
      Gooseberry.questionSetCollectionView = new QuestionSetCollectionView();
    }
    return Gooseberry.questionSetCollectionView.render();
  };

  Router.prototype.questionSet = function(name) {
    if (!Gooseberry.questionSetView) {
      Gooseberry.questionSetView = new QuestionSetView();
    }
    return Gooseberry.questionSetView.fetchAndRender(name);
  };

  Router.prototype.editQuestionSet = function(name) {
    if (!Gooseberry.questionSetEdit) {
      Gooseberry.questionSetEdit = new QuestionSetEdit();
    }
    return Gooseberry.questionSetEdit.fetchAndRender(name);
  };

  Router.prototype.questionSetResults = function(name) {
    if (!Gooseberry.questionSetResults) {
      Gooseberry.questionSetResults = new QuestionSetResults();
    }
    return Gooseberry.questionSetResults.fetchAndRender(name);
  };

  Router.prototype.userLoggedIn = function(callback) {
    return User.isAuthenticated({
      success: function(user) {
        return callback.success(user);
      },
      error: function() {
        Gooseberry.loginView.callback = callback;
        return Gooseberry.loginView.render();
      }
    });
  };

  Router.prototype.csv = function(question, startDate, endDate) {
    return this.userLoggedIn({
      success: function() {
        var csvView;
        if (User.currentUser.hasRole("reports")) {
          csvView = new CsvView;
          csvView.question = question;
          csvView.startDate = endDate;
          csvView.endDate = startDate;
          return csvView.render();
        }
      }
    });
  };

  Router.prototype.showErrorPage = function() {
    return $("#content").html("No matching route");
  };

  return Router;

})(Backbone.Router);

//# sourceMappingURL=routes.js.map
