// Generated by CoffeeScript 1.8.0
var InteractView,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

InteractView = (function(_super) {
  __extends(InteractView, _super);

  function InteractView() {
    this.render = __bind(this.render, this);
    this.send = __bind(this.send, this);
    this.addReceivedText = __bind(this.addReceivedText, this);
    this.addSentText = __bind(this.addSentText, this);
    this.checkforshortcut = __bind(this.checkforshortcut, this);
    return InteractView.__super__.constructor.apply(this, arguments);
  }

  InteractView.prototype.el = '#content';

  InteractView.prototype.events = {
    "click button#send": "send",
    "keyup textarea": "checkforshortcut"
  };

  InteractView.prototype.checkforshortcut = function(event) {
    if (event.keyCode === 13 && event.ctrlKey) {
      this.send();
      return event.stopPropogation;
    }
  };

  InteractView.prototype.addSentText = function(text) {
    $("#interactions").append("<div class='sent'>" + text + "</div>");
    return $(".latest").removeClass("latest");
  };

  InteractView.prototype.addReceivedText = function(text) {
    $("#interactions").append("<div class='received latest'>" + text + "</div>");
    return $("textarea").val("");
  };

  InteractView.prototype.send = function() {
    var textToSend;
    textToSend = $("#textToSend").val();
    if (textToSend) {
      this.addSentText(textToSend);
      return $.ajax({
        url: this.target,
        data: {
          from: "web",
          text: textToSend,
          plain: true
        },
        success: (function(_this) {
          return function(result) {
            var from, text, _ref;
            _ref = result.split(/:(.+)?/), from = _ref[0], text = _ref[1];
            return _this.addReceivedText(text);
          };
        })(this)
      });
    }
  };

  InteractView.prototype.render = function() {
    this.$el.html("<textarea id='textToSend'></textarea> <button type='button' id='send'>Send</button> <div id='interactions'></div>");
    $("textarea").val("START " + this.name);
    return $("textarea").focus();
  };

  return InteractView;

})(Backbone.View);

//# sourceMappingURL=InteractView.js.map
