// Generated by CoffeeScript 1.9.0
(function(doc) {
  if ((doc.complete != null) && doc.complete === false) {
    return emit([doc.question_set, doc.from], [doc.times_reminders_sent, doc.updated_at]);
  }
});

//# sourceMappingURL=map.js.map
