// Generated by CoffeeScript 1.9.0
(function(doc) {
  var number;
  number = doc.type === "sent" ? doc.to : doc.type === "incoming" ? doc.from : void 0;
  if (number) {
    return emit([number, doc.time], [doc.type, doc.message]);
  }
});

//# sourceMappingURL=map.js.map
